  - hosts: loadbalancer
    become: true
    tasks:
      - name: verify backend response
        uri: url=http://{{item}} return_content=yes
        with_items: "{{groups.webserver}}"
        register: app_index

      - fail: msg="index failed to return content"
        when: "'Hello, from sunny' not in item.content"
        with_items: "{{app_index.results}}"
